id: AABF5AA26
base_file: f6C77.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:18:05.802997
  last_modified_at: 2022-06-11 13:18:05.803004
